question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
    # New data
    {"text": "Ostriches can fly.", "answer": "False"},
    {"text": "Bananas grow on trees.", "answer": "False"},
    {"text": "The Great Wall of China is visible from space.", "answer": "False"},
    {"text": "Kangaroos cannot walk backwards.", "answer": "True"},
    {"text": "The Eiffel Tower was originally intended for Barcelona, Spain.", "answer": "False"},
    {"text": "Rabbits are rodents.", "answer": "False"},
    {"text": "The human brain stops growing after the age of 25.", "answer": "True"},
    {"text": "Polar bears are left-handed.", "answer": "False"},
    {"text": "The shortest war in history lasted only 38 minutes.", "answer": "True"},
    {"text": "Sharks do not have bones.", "answer": "True"},
    {"text": "The Earth is closest to the Sun in January.", "answer": "True"},
    {"text": "Octopuses have three hearts.", "answer": "True"},
    # Add more questions here if needed
]
